### ISSUE TITLE
Composer v1.x with dev-trunk: All plugin versions are 'rejected by your constraint'

### ISSUE THREAD

**Issue by jberculo** [outlandishideas/wpackagist#372]
Since this morning, my deploys stopped working while doing the composer install. For all plugins the logs now show:

```
 Problem 1
    - The requested package wpackagist-plugin/akismet dev-trunk exists as wpackagist-plugin/akismet[2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.3.0, 2.4.0, 2.4.1, 2.5.0, 2.5.1, 2.5.10, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.5.6, 2.5.7, 2.5.8, 2.5.9, 2.6.0, 2.6.1, 3.0.0, 3.0.0-RC1, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1, 3.1.1, 3.1.10, 3.1.11, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.7, 3.1.8, 3.1.9, 3.2, 3.3, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 4.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.1, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.1.7, dev-trunk] but these are rejected by your constraint.
```

I use this in the require section:
```
  "require": {
    "wpackagist-plugin/akismet": "dev-trunk",
```

I'm user composer v1.

**Comment by NoelLH** [comment]
@jberculo have you tried an update in the last hour or two? As per https://github.com/outlandishideas/wpackagist/issues/350#issuecomment-750182126 there was an unavoidable blip after the latest release while packaged data updated, which should now be resolved permanently.

I added this same package and version to a test project just now and it worked. I'm using Composer v2.x but in this case I don't think this should impact the availability of the package.

If you're still having issues it would be helpful to see your full `composer.json` / `composer.lock`.

**Comment by jberculo** [comment]
I've tried multiple times the last few hours. 

```
{
  "name": "sargasso/wordpress-composer",
  "description": "Sargasso composer",
  "type": "project",
  "authors": [
    {
      "name": "Joost Berculo",
      "role": "Head most important honcho"
    }
  ],
  "repositories": [
    {
      "type": "composer",
      "url": "https://wpackagist.org"
    }
  ],
  "minimum-stability": "dev",
  "prefer-stable": true,
  "config": {
    "sort-packages": true,
    "bin-dir": "bin"
  },
  "require": {
    "andres-montanez/magallanes": "^4.0",
    "bjornjohansen/wplang": "^0.1.0",
    "composer/installers": "^1.2",
    "drupal-composer/preserve-paths": "0.1.*",
    "johnpbloch/wordpress-core-installer": "dev-master",
    "johnpbloch/wordpress-core": "~5.0",
    "wpackagist-plugin/akismet": "dev-trunk",
 <removed rest of composer require>
  },
  "extra": {
    "installer-paths": {
      "wp-content/plugins/{$name}/": [
        "type:wordpress-plugin"
      ],
      "wp-content/themes/{$name}/": [
        "type:wordpress-theme"
      ]
    },
    "wordpress-languages": [ "nl_NL" ],
    "wordpress-language-dir": "wp-content/languages",
    "preserve-paths": [
      "wp-config.php",
      "wp-content/uploads",
      "wp-content/plugins",
      "wp-content/themes"
    ]
  },
  "scripts": {
    "post-install-cmd": [
      "rm wordpress/composer.*",
      "cp -r wordpress/* .",
      "rm -rf wordpress"
    ],
    "post-update-cmd": [
      "rm wordpress/composer.*",
      "cp -r wordpress/* .",
      "rm -rf wordpress"
    ]
  }
}
```

**Comment by jberculo** [comment]
I just did a retest, still the same problem, it fails on all 26 plugins I try to include using wpackagist. There is no composer.lock when I deploy

**Comment by NoelLH** [comment]
Just confirming I can replicate the problem with Composer v1.10.19. v2.0.8 works fine. I have no idea why and very little time left today – but will keep an eye out for PRs if you have any ideas.

**Comment by NoelLH** [comment]
This is the JSON we are serving in Production for Akismet currently: https://wpackagist.org/p/wpackagist-plugin/akismet$d3019d28dcd45d5d51dd1d8c72c21a0040ef8d49a52cb6419673ebe8d9259665.json

The `dev-trunk` key inside `packages.wpackagist-plugin/akismet` looks like:
```
dev-trunk": {
    "name": "wpackagist-plugin/akismet",
    "version": "dev-trunk",
    "version_normalized": "dev-trunk",
    "uid": "31c9742f2e40874c8db6fec049d5da98d621c0804529626b8040604072c8a58c",
    "time": "2020-12-08 22:31:33",
    "dist": {
        "type": "zip",
        "url": "https://downloads.wordpress.org/plugin/akismet.zip?timestamp=1607466693"
    },
    "source": {
        "type": "svn",
        "url": "https://plugins.svn.wordpress.org/akismet/",
        "reference": "trunk"
    },
    "homepage": "https://wordpress.org/plugins/akismet/",
    "require": {
        "composer/installers": "~1.0"
    },
    "type": "wordpress-plugin"
}
```

**Comment by NoelLH** [comment]
Obviously I want this fixed too, but would just add for anybody who urgently needs a solution that either of these – which are both arguably good practice anyway – should work around the issue in the mean time:

* pin Wpackagist packages to more specific version ranges
* upgrade to Composer v2.x, which is faster and depending on your plugin use may be backwards compatible

**Comment by jberculo** [comment]
Thanks for your help. It's already more than I hoped for :).

**Comment by NoelLH** [comment]
No probs @jberculo – I think I actually have a lead for a fix too! I downgraded Wpackagist's own Composer to v1.x and it gives me a different `"version_normalized":"9999999-dev"`.

This seems to fix v1.x locally. I will test v2.x too and prepare a PR if it looks like both work.

**Comment by NoelLH** [comment]
So it looks like [this change](https://github.com/composer/composer/issues/8323) explains the normalisation difference and why we need to old package when normalising to maintain Composer v1 compatibility.

Reading [this](https://blog.packagist.com/composer-and-default-git-branches/) I think it may be that some way down the line, we can consider recommending a special `branch-alias` for Composer v1.x users, rather than supporting it out the box, in order to enable Wpackagist to upgrade. But for now, it is clearly far too soon and I don't think there is any significant benefit to us upgrading since we only use Composer internally for the version normalisation – meaning hopefully no significant performance hit in this context from downgrading.

**Comment by NoelLH** [comment]
Seems to be working on Staging now, including with caching disabled. Current Akismet JSON data is at https://staging-wpackagist.out.re/p/wpackagist-plugin/akismet$a908cce6b2271c26dbb521588a64bdfd8747524dd77191502a4003c16e75e19e.json and shows the old style `version_normalized` for `dev-trunk`.

**Comment by NoelLH** [comment]
This is now on Production, and a full update has finished running there.

All packages should now hopefully have Composer v1 + v2 compatible metadata for packages' dev versions again.

**Comment by jberculo** [comment]
Wooh! You did it. My builds are now getting through the composer phase :). Thanks a lot for your work, and happy holidays!
